{"name": "Нельзя авторизоваться с неверным логином или паролем", "status": "passed", "steps": [{"name": "Обязательное поле: password заполнено с ошибкой", "status": "passed", "start": 1719414744588, "stop": 1719414745390}], "parameters": [{"name": "wrong_data_field", "value": "'password'"}], "start": 1719414744588, "stop": 1719414745390, "uuid": "9746ccc3-99db-4e72-aa29-2436cb5e8ff5", "historyId": "f72524cbf496b1ec3017f956358a2d4b", "testCaseId": "823ca9a1d94bdf23f4938cbc10644675", "fullName": "tests.test_login.TestPostLogin#test_cannot_login_with_wrong_data_field", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestPostLogin"}, {"name": "host", "value": "FLTP-5R3-8512"}, {"name": "thread", "value": "9196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}